### ISSUE TITLE
working in unity 5 ?

### ISSUE THREAD

**Issue by kilik128** [npruehs/bychance#5]
working in unity 5 ?

**Comment by npruehs** [comment]
Actually, it does! I've just verified everything works fine in Unity 5.0.0f4. Feel free to get back to me immediately in case you should experience any issues.

**Comment by kilik128** [comment]
Nice ! sorry to ask that's but you got demo version :<) please

**Comment by npruehs** [comment]
I can point you to the official manual: http://www.levelsbychance.com/unity/manual.pdf That should give a pretty good idea of how to work with the plugin, including editor windows and inspectors. Also, you can take a look at the open-source repository of the underlying framework: https://github.com/npruehs/bychance This is basically the level generation algorithm without the Unity editor windows on top.
