### ISSUE TITLE
Possible Maximum limit for chunks?

### ISSUE THREAD

**Issue by frieddumplings** [npruehs/bychance#9]
I just noticed - there is a minimum required limit per chunk, but as far as I can see there is no maximum limit. Would it be possible to implement something like this? So we can limit the generation of specific chunks to a set number. I don't mind working on it a little myself if I get some pointers - but I have gone through the API references and I'm not sure where to start.

Cheers,

**Comment by npruehs** [comment]
Hey @frieddumplings! The easiest way would be to create an own `ByChanceChunkDistribution` (see page 12 of the manual: http://www.levelsbychance.com/unity/manual.pdf) Cast `level` to `Level3D` and check your chunk count, then return 0 as weight if you don't want to use that chunk.

The script could look somehow like this (not tested, not optimized):

        public class MaximumChunkCountChunkDistribution : ByChanceChunkDistribution
        {
            public int MaximumCount = 1;

            public string RestrictedChunkTag;

            public override int GetEffectiveWeight(Context freeLevelContext, Context chunkCandidateContext, object level)
            {
                // Check parameters.
                if (MaximumCount <= 0 || string.IsNullOrEmpty(this.RestrictedChunkTag))
                {
                    return base.GetEffectiveWeight(freeLevelContext, chunkCandidateContext, level);
                }

                // Check passed chunks.
                if (freeLevelContext.Source.Tag != this.RestrictedChunkTag && chunkCandidateContext.Source.Tag != this.RestrictedChunkTag)
                {
                    return base.GetEffectiveWeight(freeLevelContext, chunkCandidateContext, level);
                }

                // Check level state.
                var level3D = (Level3D)level;
                var chunkCount = level3D.Count(chunk => chunk.Tag == this.RestrictedChunkTag);
                return chunkCount < this.MaximumCount
                           ? base.GetEffectiveWeight(freeLevelContext, chunkCandidateContext, level)
                           : 0;
            }
        }

Add that script to your level generator game object (or any child). I'm gonna add such a script in the next major release. Please tell me if that works for your case!

**Comment by frieddumplings** [comment]
Hi! Yes this works quite well, a few errors pointing to level generator which I have added in below. But that kind of what is intended. I did manage to do something similar by modifying the Anchor script to accept the chunk (uncasted) and level then clearing the targets if they go past a max limit. Seems to work as well. Maybe some sort of distance check would be nice too, so we dont for example get an end cell right next to the start cell. 

bychancefillanchor.cs ->
```
 public void FillAnchors(ByChanceChunkTemplate chunk, Random2 random, Level3D level, Chunk chunkT)
...etc

private void FillAnchor(ByChanceChunkTemplate chunk, UnityAnchor anchor, Random2 random, Level3D level, Chunk chunkT)
        {
            if (this.MaxOccurs > 0 && this.Occurs >= this.MaxOccurs)
            {
                for(int i = 0; i < chunkT.Contexts.Count(); i++)
                {
                    chunkT.Contexts.ElementAt(i).ClearTarget();
                }
                DestroyImmediate(chunk.gameObject);
                return;
            }
```

```
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: maxExclusive
ByChance.Core.Random2.NextInt32 (Int32 maxExclusive) (at Assets/ByChance/Framework/Scripts/Core/Random2.cs:151)
ByChance.Core.LevelGenerator.AddChunk[ChunkTemplate3D,Chunk3D] (ByChance.Core.ChunkLibrary`1 chunkLibrary, ByChance.Core.Level`1 level, ByChance.Core.Random2 random, ByChance.Core.Context freeContext) (at Assets/ByChance/Framework/Scripts/Core/LevelGenerator.cs:250)
ByChance.Core.LevelGenerator.AddChunk[ChunkTemplate3D,Chunk3D] (ByChance.Core.ChunkLibrary`1 chunkLibrary, ByChance.Core.Level`1 level, ByChance.Core.Random2 random) (at Assets/ByChance/Framework/Scripts/Core/LevelGenerator.cs:113)
ByChance.Levels3D.LevelGenerator3D.AddChunk (ByChance.Levels3D.ChunkLibrary3D chunkLibrary, ByChance.Levels3D.Level3D level, ByChance.Core.Random2 random) (at Assets/ByChance/Framework/Scripts/Levels3D/LevelGenerator3D.cs:67)
ByChance.Unity.ByChanceLevelGenerator.OnRenderObject () (at Assets/ByChance/Framework/Scripts/Unity/ByChanceLevelGenerator.cs:584)
UnityEditor.DockArea:OnGUI()

```

**Comment by npruehs** [comment]
Okay, will take a look at that. Might happen if there are chunk candidates, but all are discarded because of the maximum limit.

**Comment by npruehs** [comment]
Actually, there's an example of including distance in the readme: https://github.com/npruehs/bychance#modifying-effective-chunk-weights

Your way works as well. However, you'll prevent that part of the level from being filled by another chunk, which technically would be possible of course :)

**Comment by npruehs** [comment]
Okay, my bad. Should be ByChanceContextAlignmentRestriction. This will essentially skip the chunks, even saving the weight test for better performance. Here's the script:

    /// <summary>
    ///   Prevents chunks from being added too often to a level.
    /// </summary>
    public class MaximumChunkCountContextAlignmentRestriction : ByChanceContextAlignmentRestriction
    {
        #region Fields

        /// <summary>
        ///   Maximum number of chunks with the specified name.
        /// </summary>
        public int MaximumCount = 1;

        /// <summary>
        ///   Name of the chunk to restrict.
        /// </summary>
        public string RestrictedChunk;

        #endregion

        #region Public Methods and Operators

        /// <summary>
        ///   Checks if the two passed contexts can be aligned, or not.
        ///   This relation is assumed to be symmetric i.e., if <c>first</c> and <c>second</c>
        ///   can be aligned, then <c>second</c> and <c>first</c> can be aligned, too.
        /// </summary>
        /// <param name="first">First context to check.</param>
        /// <param name="second">Second context to check.</param>
        /// <param name="level">Current generated level.</param>
        /// <returns><c>true</c>, if the two contexts can be aligned, and <c>false</c> otherwise.</returns>
        public override bool CanBeAligned(Context first, Context second, object level)
        {
            // Check parameters.
            if (this.MaximumCount <= 0)
            {
                UnityEngine.Debug.LogError("MaximumCount must be greater than zero.", this);
                return true;
            }

            if (string.IsNullOrEmpty(this.RestrictedChunk))
            {
                UnityEngine.Debug.LogError("Restricted chunk name must not be empty.", this);
                return true;
            }

            // Check passed chunks.
            if (first.Source.Tag != this.RestrictedChunk && second.Source.Tag != this.RestrictedChunk)
            {
                return true;
            }

            // Check level state.
            var level3D = (Level3D)level;
            var chunkCount = level3D.Count(chunk => chunk.Tag == this.RestrictedChunk);
            return chunkCount < this.MaximumCount;
        }

        #endregion
    }

**Comment by frieddumplings** [comment]
Yes, I have tested and this seems to work perfectly. And they can be stacked too for different chunks which is really good. I should probably read the comments a bit more closely as I completely missed the note on distance, thanks for handling my request so quickly!

No errors as of yet, I will test further later today.  
Also - for some fun I'm also testing the generator on a sub 200$ potato laptop. Works perfectly so far for smaller levels at least. Haven't seen any major performance hikes (unless the iterations when generating levels fail which is to be expected). I'm really happy with this purchase. Much appreciated!

![a3](https://cloud.githubusercontent.com/assets/12145555/19658402/8929e5ee-9a73-11e6-92b6-f9ea3665be95.jpg)


Cheers.

**Comment by npruehs** [comment]
Glad to help! :) Performance is an interesting point, if you run into issues with that, feel free to send me a profiler snapshot. Also, when you've finished your game, I'd be happy to hear about it!
